version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www
hooks:
  ApplicationStop:
    - location: scripts/null.sh
      timeout: 30
      runas: root
  BeforeInstall:
    - location: scripts/null.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/null.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/null.sh    
      timeout: 30
      runas: root
  ValidateService:
    - location: scripts/null.sh
      timeout: 30
      runas: root
